<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mxn_team"
 *
 * Auto generated by Extension Builder 2020-06-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'mxn_team',
    'description' => 'test',
    'category' => 'plugin',
    'author' => '',
    'author_email' => '',
    'state' => 'alpha',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.9.99',
            'news' => '',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
